export default (syntax) => ({
   name: 'DraculaPhilip',
   type: 'dark',
   colors: {
      // ---------------------------
      // Editor Base Colors
      // ---------------------------
      'selection.background': '#bd93f9',
      'descriptionForeground': '#f8f8f2b3',
      'errorForeground': '#ff5555',
      'widget.shadow': '#00000044',
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editor.lineHighlightBorder': '#44475a',
      'editor.lineHighlightBackground': null,
      'editorLineNumber.foreground': '#6272a4',
      'editorLineNumber.activeForeground': '#8be9fd',
      'editorCursor.foreground': '#85efff',
      'editorLineNumber.dimmedForeground': '#44475a',
      // ---------------------------
      // Badge
      // ---------------------------
      'badge.background': '#44475a',
		'badge.foreground': '#f8f8f2',
      'profileBadge.background': '#4d4d4d',
		'profileBadge.foreground': '#ffffff',
      // ---------------------------
      // Activity Bar
      // ---------------------------
		'activityBar.activeBorder': '#ff79c680',
		'activityBar.background': '#282a36',
		'activityBar.foreground': '#f8f8f2',
		'activityBar.inactiveForeground': '#6272a4',
      'activityBar.activeBackground': '#bd93f910',
      'activityBar.border': '#0f1415',
      'activityBar.dropBackground': '#282a36',
      'activityBar.foreground': '#f8f8f2',
      'activityBar.inactiveForeground': '#6272a4',
      'activityBarBadge.background': '#ff79c6',
      'activityBarBadge.foreground': '#f8f8f2',
      // ---------------------------
      // Sidebar
      // ---------------------------
      'sideBar.background': '#041d20',
      'sideBar.foreground': '#a5b5b5',
      'sideBar.border': '#0f1415',
      'sideBar.dropBackground': '#041d20',
      'sideBarTitle.foreground': '#a5b5b5',
      'sideBarSectionHeader.background': '#083d44',
      'sideBarSectionHeader.foreground': '#a5b5b5',
      'sideBarSectionHeader.border': '#0f1415',
      // ---------------------------
      // Status Bar
      // ---------------------------
	   'statusBar.background': '#21222c',
      'statusBar.foreground': '#f8f8f2',
      'statusBar.border': 'null',
      'statusBar.debuggingBackground': '#ff5555',
      'statusBar.debuggingForeground': '#191a21',
      'statusBar.debuggingBorder': 'null',
      'statusBar.focusBorder ':  '#f8f8f2',
      'statusBar.noFolderForeground': '#f8f8f2',
      'statusBar.noFolderBackground': '#191a21',
      'statusBar.noFolderBorder': 'null',
      'statusBarItem.activeBackground': '#19bacc45',
      'statusBarItem.hoverBackground': '#062e32',
      'statusBarItem.prominentBackground': '#ff5555',
      'statusBarItem.prominentHoverBackground': '#ffb86c',
      'statusBarItem.errorBackground': '#cc0000',
      'statusBarItem.errorForeground': '#ffffff',      
      // ---------------------------
      // Button
      // ---------------------------
      'button.background': '#44475a',
      'button.foreground': '#f8f8f2',
      'button.hoverBackground': '#52556c',
      'button.secondaryBackground': '#282a36',
		'button.secondaryForeground': '#f8f8f2',
		'button.secondaryHoverBackground': '#343746',
      'button.border': null,
		'button.hoverBackground': '#52556c',
		'button.separator': '#f8f8f266',
      // ---------------------------
      // Dropdown
      // ---------------------------
      'dropdown.background': '#073940',
      'dropdown.border': '#073940',
      'dropdown.foreground': '#87a7ab',
      // ---------------------------
      // Editor Marker Navigation
      // ---------------------------
      'editorMarkerNavigation.background': '#21222c',
		'editorMarkerNavigationError.background':'#ff5555',
      'editorMarkerNavigationError.foreground':'#ffff',
      'editorMarkerNavigationWarning.background': '#e69533',
		'editorMarkerNavigationInfo.background': '#73c991',
		'editorMarkerNavigationInfo.headerBackground': '#73c991',
		'editorMarkerNavigationWarning.headerBackground': '#e69533',

      // ---------------------------
      // Errors and warnings
      // ---------------------------
      'editorError.border': '#052529',
      'editorError.foreground': '#ff5555',
      'editorError.background': null,
		'editorError.border': null,
      'editorWarning.background': null,
		'editorWarning.border': '#052529',
      'editorWarning.foreground': '#e69533',
      'editorInfo.background': null,
		'editorInfo.border': null,
		'editorInfo.foreground': '#8be9fd',
      'editorHint.border': null,
		'editorHint.foreground': '#eeeeeeb3',
      'editorHint.border': '#49e9a600',
      'editorHint.foreground': '#49e9a6',
      // ---------------------------
      // Editor Groups and Tabs
      // ---------------------------
      'editorGroup.dropBackground': '#44475a70',
      'editorGroup.emptyBackground': '#5f6b6d33',
      'editorGroup.focusedEmptyBorder': null,
      'editorGroup.border': '#444444',
      'editorGroup.dropBackground': '#5f6b6d33',
      'editorGroup.dropIntoPromptBackground': '#21222c',
		'editorGroup.dropIntoPromptBorder': null,
		'editorGroup.dropIntoPromptForeground': '#f8f8f2',
		
      // ---------------------------
      // Editor Group Header
      // ---------------------------
      'editorGroupHeader.noTabsBackground': '#282a36',
      'editorGroupHeader.tabsBackground': '#21222c',
      'editorGroupHeader.tabsBorder': '#21222c',
      'editorGroupHeader.border': null,
		'editorGroupHeader.tabsBorder': null,
      // ---------------------------
      // Editor Tabs
      // ---------------------------
      'tab.activeBackground': '#282a36',
      'tab.activeBorder': null,
      'tab.unfocusedActiveBackground': '#0e1e20',
		'tab.activeBorderTop': '#ff79c680',
		'tab.activeForeground': '#f8f8f2',
		'tab.border': '#191a21',
      'tab.activeModifiedBorder': '#3399cc',
      'tab.unfocusedActiveModifiedBorder': '#3399cc80',
		'tab.inactiveBackground': '#21222c',
		'tab.inactiveForeground': '#6272a4',
      'tab.unfocusedActiveForeground': '#f8f8f280',
      'tab.unfocusedActiveBackground': '#282a36',
      'tab.unfocusedInactiveForeground': '#6272a480',
      'tab.unfocusedInactiveBackground': '#21222c',
		'tab.unfocusedInactiveModifiedBorder': '#3399cc40',
      'tab.activeBorder': '#052529',
      'tab.unfocusedActiveBorder': '#052529',
      'tab.unfocusedActiveBorderTop': '#ff79c640',
      'tab.unfocusedHoverBackground': '#169fb121',
		'tab.unfocusedHoverBorder': null,
		'tab.unfocusedHoverForeground': null,
      'tab.unfocusedInactiveBackground': '#21222c',
		'tab.unfocusedInactiveModifiedBorder': '#3399cc40',
		'tab.hoverBackground': null,
		'tab.hoverBorder': null,
		'tab.hoverForeground': null,
		'tab.inactiveModifiedBorder': '#3399cc80',
		'tab.lastPinnedBorder': '#585858',
      // ---------------------------
      // Text Colors
      // ---------------------------
      'textBlockQuote.background': '#041d20',
      'textBlockQuote.border': '#16a3b6',
      'textCodeBlock.background': '#041d20',
      'textLink.activeForeground': '#40d4e7',
      'textLink.foreground': '#40d4e7',
      'textPreformat.foreground': '#e4b781',
      'textSeparator.foreground': '#041d20',
      // ---------------------------
      // Welcome Page
      // ---------------------------
      'walkThrough.embeddedEditorBackground': '#041d20',
      'welcomePage.buttonBackground': '#041d20',
      'welcomePage.buttonHoverBackground': '#003742',
      // ---------------------------
      // Input Control
      // ---------------------------
      'input.background': '#052529',
      'input.border': '#073940',
      'input.foreground': '#CDD3DE',
      'input.placeholderForeground': '#87a7ab',
      'inputOption.activeBorder': '#169fb1',
      'inputValidation.errorForeground': '#ff4000',
      'inputValidation.errorBackground': '#501502ee',
      'inputValidation.errorBorder': '#691c02',
      'inputValidation.infoForeground': '#40d4e7',
      'inputValidation.infoBackground': '#0f6e7bee',
      'inputValidation.infoBorder': '#148f9f',
      'inputValidation.warningForeground': '#e69533',
      'inputValidation.warningBackground': '#82694acc',
      'inputValidation.warningBorder': '#a88457',
      // ---------------------------
      // Editor Widgets
      // ---------------------------
      'editorWidget.background': '#073940',
      'editorWidget.border': '#0f1415',
      'editorHoverWidget.background': '#073940',
      'editorHoverWidget.border': '#0f1415',
      'editorSuggestWidget.background': '#073940',
      'editorSuggestWidget.border': '#0f1415',
      'editorSuggestWidget.foreground': '#87a7ab',
      'editorSuggestWidget.highlightForeground': '#40d4e7',
      'editorSuggestWidget.selectedBackground': '#0e6671',
      // ---------------------------
      // Gutter
      // ---------------------------
      'editorGutter.background': '#052529',
      'editorGutter.addedBackground': '#8ce99a',
      'editorGutter.deletedBackground': '#e34e1c',
      'editorGutter.modifiedBackground': '#e0c184',
      // ---------------------------
      // Selection Colors
      // ---------------------------
      'editor.selectionBackground': '#169fb144',
      'editor.selectionHighlightBackground': '#49ace944',
      'editor.inactiveSelectionBackground': '#0e657155',
      'editor.wordHighlightStrongBackground': '#cc990033',
      'editor.wordHighlightBackground': '#e4b78133',
      'editor.findMatchBackground': '#40bf6a11',
      'editor.findMatchHighlightBackground': '#0e667179',
      'editor.findRangeHighlightBackground': '#49e9a633',
      'editor.hoverHighlightBackground': '#169fb13f',
      'editor.lineHighlightBackground': '#083d44ee',
      'editor.lineHighlightBorder': '#083d44',
      'editor.rangeHighlightBackground': '#083d44a1',
      'editorLink.activeForeground': '#14a5ff',
      'editorWhitespace.foreground': '#ffffff21',
      'editorIndentGuide.background': '#223b3f',
      'editorIndentGuide.activeBackground': '#3e6f74',
      'editorBracketMatch.background': '#169fb122',
      'editorBracketMatch.border': '#169fb1',
      'editorRuler.foreground': '#29484c',
      // ---------------------------
      // Code Lens
      // ---------------------------
      'editorCodeLens.foreground': '#507b95',
      // ---------------------------
      // Integrated Terminal Colors
      // ---------------------------
      'terminal.ansiBlack': '#324a4d',
      'terminal.ansiRed': '#e66533',
      'terminal.ansiGreen': '#49e9a6',
      'terminal.ansiYellow': '#e4b781',
      'terminal.ansiBlue': '#49ace9',
      'terminal.ansiMagenta': '#df769b',
      'terminal.ansiCyan': '#49d6e9',
      'terminal.ansiWhite': '#b2cacd',
      'terminal.ansiBrightBlack': '#47686c',
      'terminal.ansiBrightRed': '#e97749',
      'terminal.ansiBrightGreen': '#60ebb1',
      'terminal.ansiBrightYellow': '#e69533',
      'terminal.ansiBrightBlue': '#60b6eb',
      'terminal.ansiBrightMagenta': '#e798b3',
      'terminal.ansiBrightCyan': '#60dbeb',
      'terminal.ansiBrightWhite': '#c1d4d7',
      'terminal.background': '#03191b',
      'terminal.foreground': '#b2cacd',
      'terminalCursor.background': '#03191b',
      'terminalCursor.foreground': '#b2cacd',
      // ---------------------------
      // Merge Conflicts
      // ---------------------------
      'merge.border': '#05252900',
      'merge.currentContentBackground': '#85f1ff22',
      'merge.currentHeaderBackground': '#85f1ff44',
      'merge.incomingContentBackground': '#9d92f222',
      'merge.incomingHeaderBackground': '#9d92f244',
      'merge.commonContentBackground': '#ffc18022',
      'merge.commonHeaderBackground': '#ffc18044',
      'editorOverviewRuler.currentContentForeground': '#85f1ff44',
      'editorOverviewRuler.incomingContentForeground': '#9d92f244',
      'editorOverviewRuler.commonContentForeground': '#ffc18044',
      'editorOverviewRuler.border': '#052529',
      // ---------------------------
      // Notification Colors
      // ---------------------------
      'notificationCenter.border': '#073940',
      'notificationCenterHeader.foreground': '#87a7ab',
      'notificationCenterHeader.background': '#073940',
      'notificationToast.border': '#073940',
      'notifications.foreground': '#CDD3DE',
      'notifications.background': '#073940',
      'notifications.border': '#073940',
      'notificationLink.foreground': '#87a7ab',
      // ---------------------------
      // Diff
      // ---------------------------
      'diffEditor.insertedTextBackground': '#50fa7b20',
      'diffEditor.removedTextBackground': '#ff555550',
      // ---------------------------
      // Debug
      // ---------------------------
      'debugToolBar.background': '#041d20',
      'debugExceptionWidget.background': '#041d20',
      'debugExceptionWidget.border': '#16a3b6',
      // ---------------------------
      // Extensions
      // ---------------------------
      'extensionButton.prominentBackground': '#50fa7b90',
      'extensionButton.prominentForeground': '#f8f8f2',
      'extensionButton.prominentHoverBackground': '#50fa7b60',
      'focusBorder': '#6272a4',
      'foreground': '#f8f8f2',
      // ---------------------------
      // Panel
      // ---------------------------
      'panel.background': '#03191b',
      'panel.border': '#0e6671',
      'panelTitle.activeBorder': '#0e6671',
      'panelTitle.activeForeground': '#40d4e7',
      'panelTitle.inactiveForeground': '#87a7ab',
      // ---------------------------
      // Peek View Colors
      // ---------------------------
      'peekView.border': '#169fb1',
      'peekViewEditor.background': '#002124',
      'peekViewEditor.matchHighlightBackground': '#00718079',
      'peekViewEditor.matchHighlightBorder': '#007180cc',
      'peekViewEditorGutter.background': '#002124',
      'peekViewResult.background': '#041d20',
      'peekViewResult.fileForeground': '#e4b781',
      'peekViewResult.lineForeground': '#87a7ab',
      'peekViewResult.matchHighlightBackground': '#073940',
      'peekViewResult.selectionBackground': '#073940',
      'peekViewResult.selectionForeground': '#87a7ab',
      'peekViewTitle.background': '#041d20',
      'peekViewTitleDescription.foreground': '#87a7ab',
      'peekViewTitleLabel.foreground': '#e4b781',
      // ---------------------------
      // Progress Bar
      // ---------------------------
      'progressBar.background': '#40d4e7',
      // ---------------------------
      // Scroll Bar
      // ---------------------------
      'scrollbar.shadow': '#00000044',
      'scrollbarSlider.activeBackground': '#169fb1ad',
      'scrollbarSlider.background': '#6a90955b',
      'scrollbarSlider.hoverBackground': '#169fb162',
      // ---------------------------
      // Git status colors in File Explorer
      // ---------------------------
      'gitDecoration.addedResourceForeground': '#16b673',
      'gitDecoration.modifiedResourceForeground': '#49e9a6',
      'gitDecoration.deletedResourceForeground': '#e34e1c',
      'gitDecoration.untrackedResourceForeground': '#40d4e7',
      'gitDecoration.ignoredResourceForeground': '#5b858b',
      'gitDecoration.conflictingResourceForeground': '#e4b781',
      // ---------------------------
      // Quick Picker
      // ---------------------------
      'pickerGroup.border': '#0e6671',
      'pickerGroup.foreground': '#169fb1',
      // ---------------------------
      // Lists and Trees
      // ---------------------------
      'list.activeSelectionBackground': '#0e6671',
      'list.activeSelectionForeground': '#ebfdff',
      'list.dropBackground': '#00404d',
      'list.focusBackground': '#00404d',
      'list.focusForeground': '#ebfdff',
      'list.highlightForeground': '#40d4e7',
      'list.hoverBackground': '#0b515b',
      'list.hoverForeground': '#ebfdff',
      'list.inactiveFocusBackground': '#062d32',
      'list.inactiveSelectionBackground': '#07353b',
      'list.inactiveSelectionForeground': '#b2cacd',
      'list.errorForeground': '#e34e1c',
      'list.warningForeground': '#ffa487',
      'listFilterWidget.background': '#00404d',
      'listFilterWidget.outline': '#49e9a6',
      'listFilterWidget.noMatchesOutline': '#e34e1c',
      'tree.indentGuidesStroke': '#3e6f74',

      // ---------------------------
      // Settings Editor Colors
      // ---------------------------
      'settings.headerForeground': '#b2cacd',
      'settings.modifiedItemIndicator': '#15ac31',
      'settings.dropdownListBorder': '#0e657188',
      'settings.dropdownBackground': '#073940',
      'settings.dropdownForeground': '#0cc',
      'settings.dropdownBorder': '#073940',
      'settings.checkboxBackground': '#073940',
      'settings.checkboxForeground': '#0cc',
      'settings.checkboxBorder': '#073940',
      'settings.textInputBackground': '#073940',
      'settings.textInputForeground': '#0cc',
      'settings.textInputBorder': '#073940',
      'settings.numberInputBackground': '#041d20',
      'settings.numberInputForeground': '#7060eb',
      'settings.numberInputBorder': '#041d20',
      // ---------------------------
      // Breadcrumbs
      // ---------------------------
      'breadcrumb.foreground': '#87a7ab',
      'breadcrumb.background': '#052529',
      'breadcrumb.focusForeground': '#40d4e7',
      'breadcrumb.activeSelectionForeground': '#ebfdff',
      'breadcrumbPicker.background': '#073940',
      // ---------------------------
      // Title bar
      // Note: These colors are currently only supported on macOS.
      // ---------------------------
      'titleBar.activeBackground': '#041d20',
      'titleBar.activeForeground': '#b2cacd',
      'titleBar.inactiveBackground': '#041d20',
      'titleBar.inactiveForeground': '#87a7ab',
      // ---------------------------
      // Custom title bar and menus
      // Note: These colors are currently only supported on Windows and Linux.
      // ---------------------------
      'menu.background': '#073940',
      'menu.foreground': '#87a7ab',
      'menu.selectionBackground': '#0b515b',
      'menu.selectionForeground': '#40d4e7',
      'menu.selectionBorder': '#0b515b',
      'menu.separatorBackground': '#40d4e7',
      'menubar.selectionBackground': '#0b515b',
      'menubar.selectionForeground': '#40d4e7',
      'menubar.selectionBorder': '#0b515b',
      // ---------------------------
      // Snippets
      // ---------------------------
      'editor.snippetTabstopHighlightBackground': '#03181b',
      'editor.snippetTabstopHighlightBorder': '#042124',
      'editor.snippetFinalTabstopHighlightBackground': '#03181b',
      'editor.snippetFinalTabstopHighlightBorder': '#042124',
      // ---------------------------
      // Minimap
      // ---------------------------
      'minimap.findMatchHighlight': '#49d6e9ee',
      'minimap.errorHighlight': '#e34e1cee',
      'minimap.warningHighlight': '#e69533ee',
      'minimapGutter.addedBackground': '#16b673',
      'minimapGutter.modifiedBackground': '#49e9a6',
      'minimapGutter.deletedBackground': '#e34e1c',
      'minimap.background': '#05252999',
   },
   tokenColors: syntax,
});
